### ISSUE TITLE
Cannot add numerical attrribute as first column

### ISSUE THREAD

**Issue by mstreit** [Caleydo/mothertable#288]
Adding a categorical column first and then adding a numerical one works though.

```
Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at NumberColumn.<anonymous> (AVectorColumn.ts:81)
    at step (tslib.es6.js:91)
    at Object.next (tslib.es6.js:72)
    at fulfilled (tslib.es6.js:62)
(anonymous) @ AVectorColumn.ts:81
step @ tslib.es6.js:91
(anonymous) @ tslib.es6.js:72
fulfilled @ tslib.es6.js:62
ColumnManager.ts:486 Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at ColumnManager.multiformsInGroup (http://localhost:8080/app.js:31386:33)
    at http://localhost:8080/app.js:31615:19
    at Array.forEach (native)
    at ColumnManager.updateAggregationLevelForRow (http://localhost:8080/app.js:31614:22)
    at ColumnManager.<anonymous> (http://localhost:8080/app.js:31422:34)
    at step (http://localhost:8080/app.js:108:23)
    at Object.next (http://localhost:8080/app.js:89:53)
    at http://localhost:8080/app.js:82:71
    at Object.__awaiter [as a] (http://localhost:8080/app.js:78:12)
    at ColumnManager.calColHeight (http://localhost:8080/app.js:31407:72)
ColumnManager.multiformsInGroup @ ColumnManager.ts:486
(anonymous) @ ColumnManager.ts:677
ColumnManager.updateAggregationLevelForRow @ ColumnManager.ts:676
(anonymous) @ ColumnManager.ts:518
step @ tslib.es6.js:91
(anonymous) @ tslib.es6.js:72
(anonymous) @ tslib.es6.js:65
__awaiter @ tslib.es6.js:61
ColumnManager.calColHeight @ ColumnManager.ts:508
(anonymous) @ ColumnManager.ts:459
step @ tslib.es6.js:91
(anonymous) @ tslib.es6.js:72
fulfilled @ tslib.es6.js:62
ColumnManager.ts:486 Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at ColumnManager.multiformsInGroup (http://localhost:8080/app.js:31386:33)
    at http://localhost:8080/app.js:31615:19
    at Array.forEach (native)
    at ColumnManager.updateAggregationLevelForRow (http://localhost:8080/app.js:31614:22)
    at ColumnManager.<anonymous> (http://localhost:8080/app.js:31422:34)
    at step (http://localhost:8080/app.js:108:23)
    at Object.next (http://localhost:8080/app.js:89:53)
    at http://localhost:8080/app.js:82:71
    at Object.__awaiter [as a] (http://localhost:8080/app.js:78:12)
    at ColumnManager.calColHeight (http://localhost:8080/app.js:31407:72)
```

**Comment by mstreit** [comment]
Also a problem in deployed demo system.

**Comment by thinkh** [comment]
Is fixed with PR https://github.com/Caleydo/mothertable/pull/291.
